### ISSUE TITLE
Currency symbol vs. Currency code

### ISSUE THREAD

**Issue by TomCat3** [zlogic/vogon#2]
When attempting to create an account using US Dollars or set the user account to default to US Dollars, an error occurs.  The error is a result of a deserialization issue where the server is receiving $ instead of USD.   This would be a problem for any Currency where the symbol and currency code are not the same.  Currency objects can be constructed using the currency code, but the JSON payload is giving the currency symbol.   I was able to work-around this by changing the following in CurrencyFull.java, although incorrect semantically and possibly in other ways.

	public String getSymbol() {
		return currency.getCurrencyCode();
	}

Error is below:

HTTP error: 400({"timestamp":"2015-12-14","status":400,"error":"Bad Request","exception":"org.springframework.http.converter.HttpMessageNotReadableException","message":"Could not read document: Can not construct instance of java.util.Currency from String value '$': not a valid textual representation\n at [Source: java.io.PushbackInputStream@64ca5adb; line: 1, column: 29] (through reference chain: org.zlogic.vogon.data.VogonUser[\"defaultCurrency\"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.util.Currency from String value '$': not a valid textual representation\n at [Source: java.io.PushbackInputStream@64ca5adb; line: 1, column: 29] (through reference chain: org.zlogic.vogon.data.VogonUser[\"defaultCurrency\"])","path":"/service/user"})

**Comment by zlogic** [comment]
Thanks for the details! In my setup the currency code and currency symbol were always the same so there was no clear symbol/code distinction. 
I've fixed it, almost the same as your workaround, but am using the "currencyCode" name.
