### ISSUE TITLE
Would like to use Vogon with postgresql db

### ISSUE THREAD

**Issue by javadre** [zlogic/vogon#3]
I'm trying to use Vogon  in Tomcat. It works with embedded H2 database. Can someone provide details on getting Vogon to use postgresql database. I have setup a hibernate.properties in WEB-INF/classes. But, I'm trying to get hibernate to use postgresql and not H2 embedded db. So far code only works with H2 database. I am a system administrator interested in using the application to store personal finance. I think I could import data into a Postgresql database a lot better than using the H2 database. Any help would be great. -Andre

**Comment by zlogic** [comment]
Vogon tries to auto-detect configuration for "cloud" environments (Heroku, Openshift, Azure) (see [ServerTypeDetector.java] (/zlogic/vogon/tree/master/vogon-web/vogon-web-service/src/main/java/org/zlogic/vogon/web/ServerTypeDetector.java)).

Depending on the detected server type and environment, either H2 or Postgres is used. My suggestion would be to try to trick Vogon to think it's running in a Postgres-enabled OpenShift deployment. The database is configured via [PersistenceConfiguration.java] (/zlogic/vogon/tree/master/vogon-web/vogon-web-service/src/main/java/org/zlogic/vogon/web/PersistenceConfiguration.java)) and all hibernate properties are ignored/overridden by that file.

Try setting the environment variables:

`OPENSHIFT_POSTGRESQL_DB_URL` (the connection URL, without the DB name)
`OPENSHIFT_APP_NAME` (to the database name)
`OPENSHIFT_JBOSSEWS` (if you are running Vogon as standalone, this makes it think it runs in OpenShift's Tomcat cartridge)

I may consider adding a dedicated Postgres configuration option if this is a highly wanted feature. But to reiterate, most Hibernate/JPA options are configured during runtime. This makes it possible to just create an app in any supported cloud provider, upload the WAR file and no additional configuration steps!

**Comment by javadre** [comment]
Sorry for delay of a few weeks, and Happy New Year and thank you! for your help and your time. I really do like Vogon I have seen other programs in Windows/.NET/ASP in the past, and nothing was even close to the speed of doing graphing and accessing a database as in Java/Spring. 
I have been using my time and setting up an openShift environment. As you suggested the Vogon app does detect the "cloud" environments. It was able to build a Postgres DB. Springboot detected it from the openShift environment parameters. Then, I deployed the vogon-web-tomcat-2.1 war and Vogon finally is up and running using a JBoss module/openShift. Thank you

**Comment by zlogic** [comment]
Thank you for the kind words! I'm glad my pet project is actually useful/helpful :)
